[tox]
requires =
  tox>=4
  tox-uv
envlist =
  py31{0,1,2,3,4}-{full,pre}
  py310-min
skip_missing_interpreters = true

# Configuration that allows us to split tests across GitHub runners effectively
[gh-actions]
python =
  3.10: py310
  3.11: py311
  3.12: py312
  3.13: py313
  3.14: py314

[gh-actions:env]
DEPENDS =
  min: min
  full: full
  pre: pre

CHECK =
  style: style
  spellcheck: spellcheck
  type: type

[testenv]
description = Pytest with coverage
labels = test
pip_pre =
  pre: true
pass_env =
  # getpass.getuser() sources for Windows:
  LOGNAME
  USER
  LNAME
  USERNAME
  # Pass user color preferences through
  PY_COLORS
  FORCE_COLOR
  NO_COLOR
  CLICOLOR
  CLICOLOR_FORCE
extras =
  cli
runner =
  full: uv-venv-lock-runner
  !full: uv-venv-runner
dependency_groups =
  test
uv_resolution =
  min: lowest-direct
deps =
  pre: git+https://github.com/bids-standard/bids-specification.git\#subdirectory=tools/schemacode

commands =
  python -m pytest --doctest-modules --cov . --cov-report xml --cov-report term \
  min: -Wignore \
    --junitxml=test-results.xml {posargs}
